project:
  type: book

book:
  title: "Introduction to Statistical Modelling"
  author: "Joris Vankerschaver"
  date: "2023/02/25"
  chapters:
    - index.qmd
    #- intro.qmd
    #- regression.qmd
    - pca.qmd
    #- nonlinear.qmd
    - references.qmd
  appendices:
    - datasets.qmd
  body-footer: |
    These coures notes are made available under the [Creative Commons BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    default-image-extension: svg
  pdf:
    documentclass: scrreprt
    default-image-extension: pdf
    execute:
      echo: false
    #fig-height: 2.5
    #fig-width: 4.5
