project:
  type: book

book:
  title: "Introduction to Statistical Modelling"
  author: "Joris Vankerschaver"
  date: "12/14/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - regression.qmd
    - pca.qmd
    - nonlinear.qmd
    - references.qmd
  appendices:
    - datasets.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
