project:
  type: book

book:
  title: "book"
  author: "Jane Doe"
  date: "12/14/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - regression.qmd
    - pca.qmd
    - nonlinear.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



